### PR TITLE
Fix mermaid

### PR DESCRIPTION
**Pull request by elsand**

### CODE REVIEW

**Comment by altinnadmin** [comment]
@elsand Why should we put mermaid JS directly into a markdown file?
Doesn't the [mermaid shortcode](https://docdock.vjeantet.fr/shortcodes/mermaid/) work anymore?

**Comment by elsand** [comment]
@altinnadmin The mermaid shortcode is used, but Docs does nothing to adjust the default layout. This particular graph breaks the layout of the page, and the js unbreaks it.

**Comment by altinnadmin** [comment]
@elsand Ah, wouldn't it then be better to fix it [here](https://github.com/Altinn/docs/blob/4a60daf843e576e126e870f3170bff67c5aac034/themes/hugo-theme-altinn/layouts/partials/footer.html#L91) for all pages using Mermaid?

**Review by altinnadmin — APPROVED** [review]
:shipit:

**Comment by elsand** [comment]
@altinnadmin Apparently noone else is using mermaid, so I've added this as a default and added a simple override mechanism.

**Pull request merged**
